### ISSUE TITLE
NullPointerException when update in DeviceListFragment.java

### ISSUE THREAD

**Issue by eileenfan** [klassm/andFHEM#1161]
//package name: li.klass.fhem
//version: 2.2.8
 java.lang.NullPointerException
 	at li.klass.fhem.fragments.core.DeviceListFragment.update(DeviceListFragment.java:154)
 	at li.klass.fhem.fragments.core.BaseFragment.onBackPressResult(BaseFragment.java:105)
 	at li.klass.fhem.activities.core.ContentHolderFragment.onBackPressResult(ContentHolderFragment.java:199)
 	at li.klass.fhem.activities.core.TopLevelFragment.back(TopLevelFragment.java:115)
 	at li.klass.fhem.activities.core.FragmentBaseActivity.onBackPressed(FragmentBaseActivity.java:374)
 	at li.klass.fhem.activities.core.FragmentBaseActivity.onBackPressed(FragmentBaseActivity.java:369)
 	at li.klass.fhem.activities.AndFHEMMainActivity.onOptionsItemSelected(AndFHEMMainActivity.java:60)
 	at android.support.v4.app.Watson.onMenuItemSelected(Watson.java:119)
 	at com.actionbarsherlock.ActionBarSherlock.callbackOptionsItemSelected(ActionBarSherlock.java:603)
 	at com.actionbarsherlock.internal.ActionBarSherlockNative.dispatchOptionsItemSelected(ActionBarSherlockNative.java:78)
 	at com.actionbarsherlock.app.SherlockFragmentActivity.onMenuItemSelected(SherlockFragmentActivity.java:205)
 	at com.android.internal.widget.ActionBarView$3.onClick(ActionBarView.java:171)
 	at android.view.View.performClick(View.java:4240)
 	at android.view.View.onKeyUp(View.java:7928)
 	at android.view.KeyEvent.dispatch(KeyEvent.java:2647)
 	at android.view.View.dispatchKeyEvent(View.java:7343)
 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1388)
 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1393)
 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1393)
 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1393)
 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1393)
 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1393)
 	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchKeyEvent(PhoneWindow.java:1933)
 	at com.android.internal.policy.impl.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1408)
 	at android.app.Activity.dispatchKeyEvent(Activity.java:2384)
 	at com.actionbarsherlock.app.SherlockFragmentActivity.dispatchKeyEvent(SherlockFragmentActivity.java:122)
 	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:1860)
 	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:3791)
 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3774)
 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3429)
 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3398)
 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3483)
 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3406)
 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3540)
 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3429)
 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3398)
 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3406)
 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3429)
 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3398)
 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3516)
 	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:3666)
 	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:1982)
 	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1698)
 	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1689)
 	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:1959)

**Comment by klassm** [comment]
Sorry, but version 2.2.8 is outdated. Please update to the current version in Google Play Store (v4.6.8)
