### ISSUE TITLE
App is frozen if device is rotated while reading/building up SVG graph output

### ISSUE THREAD

**Issue by psytester** [klassm/andFHEM#1241]
The app gets frozen if device is rotated while reading/building up any graph output.

Steps to reproduce: 
1. open any SVG plot graph
2. immediate while the data are read, but not yet finished to be displayed, rotate the device into landscape view

The screen gets black and the app is frozen.

If this happens, logcat is showing always this stacktrack for TypeCastException: null cannot be cast to non-null type org.joda.time.DateTime
```
12-22 23:27:41.224 31243 31243 I am_on_stop_called: [0,li.klass.fhem.graph.ui.GraphActivity,destroy]
12-22 23:27:41.226  4021  4021 D Tethering: NAP Supported by CSCFeature and not Wifi Model
12-22 23:27:41.228 28852 28852 D [WeatherWidget(14391)]  WeatherAppWidget: {[9C41A2EAFAAB2EF4F8363256C22FE8AD4AE79369C8C72BB729C5477D59528EBD3E391D65022658DE916D034F9F2C2E47]}
12-22 23:27:41.230 31243 31243 D ViewRootImpl@f6bfdbe[GraphActivity]: mHardwareRenderer.destroy()#4
12-22 23:27:41.230 31243 31243 D ViewRootImpl@f6bfdbe[GraphActivity]: dispatchDetachedFromWindow
12-22 23:27:41.230 28852 28852 D [WeatherWidget(14391)]  : {[CBE90F3EF23DAF7447FA950223C7E0849EC1C379F8C5CEFDE6152E98A1BB9160]}
12-22 23:27:41.231  4021 15973 D WindowManager: disposeInputChannel mInputChannel: 368329a li.klass.fhem/li.klass.fhem.graph.ui.GraphActivity (server)
12-22 23:27:41.231  4472  4555 D vol.VolumeDialogControl: onReceive ACTION_CONFIGURATION_CHANGED
12-22 23:27:41.236  4021 15973 I WindowManager_SurfaceController: Destroying surface Surface(name=li.klass.fhem/li.klass.fhem.graph.ui.GraphActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:3040 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:1148 com.android.server.wm.WindowState.removeLocked:1891 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:3003 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2963 com.android.server.wm.WindowManagerService.removeWindowLocked:2943 com.android.server.wm.WindowManagerService.removeWindowLocked:2731 com.android.server.wm.WindowManagerService.removeWindowLocked:2726 
12-22 23:27:41.237  2295  2300 I SurfaceFlinger: id=1342 Removed li.klass.fhem/li.klass.fhem.graph.ui.GraphActivity (6/8)
12-22 23:27:41.237  2295  2302 I SurfaceFlinger: id=1342 Removed li.klass.fhem/li.klass.fhem.graph.ui.GraphActivity (-2/8)
12-22 23:27:41.246  4472  4472 D ViewRootImpl@f485cf8[DockedStackDivider]: mHardwareRenderer.destroy()#4
12-22 23:27:41.251  2295  2295 I sf_frame_dur: [li.klass.fhem/li.klass.fhem.graph.ui.GraphActivity,91,4,0,0,0,0,0]
12-22 23:27:41.251  4021 15973 D InputDispatcher: Focus left window: 31243
12-22 23:27:41.251  4021 15973 D InputTransport: Input channel destroyed: fd=502
12-22 23:27:41.252  4021  4052 D WindowManager: set systemUiVisibility of statusbar : systemUiFlags= 0x608 fullscreenStackSysUiFlag= 0x0
12-22 23:27:41.253  4021 15973 D InputDispatcher: Focus entered window: 31243
12-22 23:27:41.254 31243 31243 D InputTransport: Input channel destroyed: fd=169
12-22 23:27:41.264 31243 31243 D ViewRootImpl@73ab94f[GraphActivity]: mHardwareRenderer.destroy()#4
12-22 23:27:41.264 31243 31243 D ViewRootImpl@73ab94f[GraphActivity]: dispatchDetachedFromWindow
12-22 23:27:41.265  4021  4313 D WindowManager: disposeInputChannel mInputChannel: 200bb8c li.klass.fhem/li.klass.fhem.graph.ui.GraphActivity (server)
12-22 23:27:41.266  4021  4313 I WindowManager_SurfaceController: Destroying surface Surface(name=li.klass.fhem/li.klass.fhem.graph.ui.GraphActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:3040 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:1148 com.android.server.wm.WindowState.removeLocked:1891 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:3003 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2963 com.android.server.wm.WindowManagerService.removeWindowLocked:2943 com.android.server.wm.WindowManagerService.removeWindowLocked:2731 com.android.server.wm.WindowManagerService.removeWindowLocked:2726 
12-22 23:27:41.267  2295  2302 I SurfaceFlinger: id=1340 Removed li.klass.fhem/li.klass.fhem.graph.ui.GraphActivity (4/7)
12-22 23:27:41.268  2295  2913 I SurfaceFlinger: id=1340 Removed li.klass.fhem/li.klass.fhem.graph.ui.GraphActivity (-2/7)
12-22 23:27:41.270  4021  4313 D InputDispatcher: Focus left window: 31243
12-22 23:27:41.271  4021  4313 D InputTransport: Input channel destroyed: fd=500
12-22 23:27:41.272 31243 31243 D InputTransport: Input channel destroyed: fd=154
12-22 23:27:41.281  4843  4843 I NfcP2pEventManager: changeConfiguration() in NfcService
12-22 23:27:41.284  2295  2295 I sf_frame_dur: [li.klass.fhem/li.klass.fhem.graph.ui.GraphActivity,0,1,0,0,0,0,0]
12-22 23:27:41.300 31243 31243 D TextView: setTypeface with style : 0
12-22 23:27:41.300 31243 31243 D TextView: setTypeface with style : 0
12-22 23:27:41.304 31243 31243 D AndroidRuntime: Shutting down VM
12-22 23:27:41.306 31243 31243 E li.klass.fhem.AndFHEMApplication: Uncaught Exception detected in thread Thread[main,5,main]
12-22 23:27:41.306 31243 31243 E li.klass.fhem.AndFHEMApplication: java.lang.RuntimeException: Unable to start activity ComponentInfo{li.klass.fhem/li.klass.fhem.graph.ui.GraphActivity}: kotlin.TypeCastException: null cannot be cast to non-null type org.joda.time.DateTime
12-22 23:27:41.306 31243 31243 E li.klass.fhem.AndFHEMApplication: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2984)
12-22 23:27:41.306 31243 31243 E li.klass.fhem.AndFHEMApplication: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045)
12-22 23:27:41.306 31243 31243 E li.klass.fhem.AndFHEMApplication: 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4978)
12-22 23:27:41.306 31243 31243 E li.klass.fhem.AndFHEMApplication: 	at android.app.ActivityThread.-wrap21(ActivityThread.java)
12-22 23:27:41.306 31243 31243 E li.klass.fhem.AndFHEMApplication: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1648)
12-22 23:27:41.306 31243 31243 E li.klass.fhem.AndFHEMApplication: 	at android.os.Handler.dispatchMessage(Handler.java:102)
12-22 23:27:41.306 31243 31243 E li.klass.fhem.AndFHEMApplication: 	at android.os.Looper.loop(Looper.java:154)
12-22 23:27:41.306 31243 31243 E li.klass.fhem.AndFHEMApplication: 	at android.app.ActivityThread.main(ActivityThread.java:6776)
12-22 23:27:41.306 31243 31243 E li.klass.fhem.AndFHEMApplication: 	at java.lang.reflect.Method.invoke(Native Method)
12-22 23:27:41.306 31243 31243 E li.klass.fhem.AndFHEMApplication: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
12-22 23:27:41.306 31243 31243 E li.klass.fhem.AndFHEMApplication: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
12-22 23:27:41.306 31243 31243 E li.klass.fhem.AndFHEMApplication: Caused by: kotlin.TypeCastException: null cannot be cast to non-null type org.joda.time.DateTime
12-22 23:27:41.306 31243 31243 E li.klass.fhem.AndFHEMApplication: 	at li.klass.fhem.graph.ui.GraphActivity.onCreate(Unknown Source)
12-22 23:27:41.306 31243 31243 E li.klass.fhem.AndFHEMApplication: 	at android.app.Activity.performCreate(Activity.java:6955)
12-22 23:27:41.306 31243 31243 E li.klass.fhem.AndFHEMApplication: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
12-22 23:27:41.306 31243 31243 E li.klass.fhem.AndFHEMApplication: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
12-22 23:27:41.306 31243 31243 E li.klass.fhem.AndFHEMApplication: 	... 10 more
.......
12-22 23:27:43.079  4021  4087 W WindowManager: App freeze timeout expired.
12-22 23:27:43.080  4021  4087 W WindowManager: Force clearing freeze: AppWindowToken{a1e4e19 token=Token{a2e6960 ActivityRecord{1e25963d0 u0 li.klass.fhem/.graph.ui.GraphActivity t4992}}}
12-22 23:27:43.080  4021  4087 I WindowManager: Screen frozen for +2s291ms due to AppWindowToken{a1e4e19 token=Token{a2e6960 ActivityRecord{1e25963d0 u0 li.klass.fhem/.graph.ui.GraphActivity t4992}}}
```

**Comment by klassm** [comment]
Thanks for reporting. This is fixed for the next version.
